// <auto-generated />
namespace BSE365.Repository.BSE365AuthContextMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PutConstraints : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PutConstraints));
        
        string IMigrationMetadata.Id
        {
            get { return "201605290553472_PutConstraints"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
